### ISSUE TITLE
Problema na hospedagem no now

### ISSUE THREAD

**Issue by iagobruno** [httpiago/generate-dynamic-images#2]
Ta dando problema especificamente nesse treço aqui:
https://github.com/httpiago/generate-dynamic-images/blob/d64d5939acc23297b46375578eec29f8420c3282/src/generate-html.js#L10-L14

Na execução local ta funcionando sem problemas mas o servidor do now não ta conseguindo encontrar os arquivos de template com a função "checkFileExists".

### Tentar:
- Importar o arquivo "./templates/default.js" fora da função e ver se da problema também.
- Usar essa configuração no now.json:
  ```
  "builds":
      { "src": "/src/index.js", "use": "@now/node", "config": { "maxLambdaSize": "40mb" } }
  routes: 
      { "src": "/(.+)", "dest": "/src/index.js" }
  ```

**Comment by httpiago** [comment]
Mudei para o Heroku.

**Comment by iagobruno** [comment]
Mudei para o Heroku.
